"""Constants for Night Watchman."""

DOMAIN = "night_watchman"

CONF_START = "start"
CONF_END = "end"
CONF_INTERVAL = "interval"
CONF_QUIET_MINUTES = "quiet_minutes"
CONF_NOTIFY_SERVICE = "notify_service"
CONF_ACTIVITY_ENTITIES = "activity_entities"
CONF_ACTIVITY_LIGHTS = "activity_lights"
CONF_ACTIVITY_MOTION = "activity_motion"
CONF_ACTIVITY_DOORS = "activity_doors"
CONF_INCLUDE_ACTIVITY_LIGHTS = "include_activity_lights"
CONF_TURN_OFF_ENTITIES = "turn_off_entities"
CONF_LOCK_ENTITY = "lock_entity"
CONF_CONTACT_ENTITY = "contact_entity"

SUBENTRY_LOCK = "lock_rule"
SUBENTRY_REPORT = "report_open"
